### PR TITLE
Script Outline

### LINKED ISSUE #1: Script Outline
# Hi let's make a game

One of the first steps to making our game would be to have a draft outline of the script :) 
Nata suggested that we make a little game to help women discover what type of engineering they might enjoy!

### PR DESCRIPTION
**Pull request by jammyness**
Fixes #1

### CODE REVIEW

**Comment by jammyness** [comment]
I created a new file with an outline

**Review by jammyness — COMMENTED** [review]
I don't think we should change the readme like this

**Comment by SenzeniMpofu** [comment]
This looks great. Awesome.

**Review by SenzeniMpofu — COMMENTED** [review]
Great.

**Comment by Natalia-Piedras** [comment]
Looks good

**Comment by Natalia-Piedras** [comment]
where is my "approve" or "resolve" button?!

**Pull request closed without merging**
